# This file has been generated by node2nix 1.3.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "grunt-0.4.5" = {
      name = "grunt";
      packageName = "grunt";
      version = "0.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz";
        sha1 = "56937cd5194324adff6d207631832a9d6ba4e7f0";
      };
    };
    "grunt-contrib-copy-1.0.0" = {
      name = "grunt-contrib-copy";
      packageName = "grunt-contrib-copy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-copy/-/grunt-contrib-copy-1.0.0.tgz";
        sha1 = "7060c6581e904b8ab0d00f076e0a8f6e3e7c3573";
      };
    };
    "grunt-contrib-concat-0.5.1" = {
      name = "grunt-contrib-concat";
      packageName = "grunt-contrib-concat";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-concat/-/grunt-contrib-concat-0.5.1.tgz";
        sha1 = "953c6efdfdfd2c107ab9c85077f2d4b24d31cd49";
      };
    };
    "grunt-contrib-jshint-0.12.0" = {
      name = "grunt-contrib-jshint";
      packageName = "grunt-contrib-jshint";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-jshint/-/grunt-contrib-jshint-0.12.0.tgz";
        sha1 = "f6b2f06fc715264837a7ab6c69a1ce1a689c2c29";
      };
    };
    "grunt-contrib-less-1.4.1" = {
      name = "grunt-contrib-less";
      packageName = "grunt-contrib-less";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-less/-/grunt-contrib-less-1.4.1.tgz";
        sha1 = "3bbdec0b75d12ceaa55d62943625c0b0861cdf6f";
      };
    };
    "grunt-contrib-watch-0.6.1" = {
      name = "grunt-contrib-watch";
      packageName = "grunt-contrib-watch";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-watch/-/grunt-contrib-watch-0.6.1.tgz";
        sha1 = "64fdcba25a635f5b4da1b6ce6f90da0aeb6e3f15";
      };
    };
    "crisper-2.1.1" = {
      name = "crisper";
      packageName = "crisper";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crisper/-/crisper-2.1.1.tgz";
        sha512 = "2kvx1j8a1qk6w04444rjh43hx2pq5rzfl8dgsfd9jz7spc1l90iym2mzy1dvinwr3d3iga1lv0qy47j8lah7v9c071yj5nvfkvf65yb";
      };
    };
    "vulcanize-1.16.0" = {
      name = "vulcanize";
      packageName = "vulcanize";
      version = "1.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vulcanize/-/vulcanize-1.16.0.tgz";
        sha512 = "0nw5wyay4ifj040hagllnpl9yrgh2ax9wwmj35ckchpmqvisdpmsg6w27agshh141s7r221ffn0r46hn349h1gdwydxxwww6jb4b2ad";
      };
    };
    "grunt-crisper-1.0.1" = {
      name = "grunt-crisper";
      packageName = "grunt-crisper";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-crisper/-/grunt-crisper-1.0.1.tgz";
        sha1 = "e7c091dcaff10deb0091e3035ca7e54008991fe7";
      };
    };
    "grunt-vulcanize-1.0.0" = {
      name = "grunt-vulcanize";
      packageName = "grunt-vulcanize";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-vulcanize/-/grunt-vulcanize-1.0.0.tgz";
        sha1 = "f4d6cfef274f8216c06f6c290e7dbb3b9e9e3b0f";
      };
    };
    "jshint-2.9.5" = {
      name = "jshint";
      packageName = "jshint";
      version = "2.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jshint/-/jshint-2.9.5.tgz";
        sha1 = "1e7252915ce681b40827ee14248c46d34e9aa62c";
      };
    };
    "bower-1.8.2" = {
      name = "bower";
      packageName = "bower";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower/-/bower-1.8.2.tgz";
        sha1 = "adf53529c8d4af02ef24fb8d5341c1419d33e2f7";
      };
    };
    "favico.js-0.3.10" = {
      name = "favico.js";
      packageName = "favico.js";
      version = "0.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/favico.js/-/favico.js-0.3.10.tgz";
        sha1 = "80586e27a117f24a8d51c18a99bdc714d4339301";
      };
    };
    "appenlight-client-git+https://git@github.com/AppEnlight/appenlight-client-js.git#0.5.0" = {
      name = "appenlight-client";
      packageName = "appenlight-client";
      version = "0.5.0";
      src = fetchgit {
        url = "https://git@github.com/AppEnlight/appenlight-client-js.git";
        rev = "b1d6853345dc3e96468b34537810b3eb77e0764f";
        sha256 = "7faa9b65033fd94789d50fee612f4ac0da29f4f99d5e9523a5e9c1109aa7a961";
      };
    };
    "async-0.1.22" = {
      name = "async";
      packageName = "async";
      version = "0.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.1.22.tgz";
        sha1 = "0fc1aaa088a0e3ef0ebe2d8831bab0dcf8845061";
      };
    };
    "coffee-script-1.3.3" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz";
        sha1 = "150d6b4cb522894369efed6a2101c20bc7f4a4f4";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha1 = "2423fe6678ac0c5dae8852e5d0e5be08c997abcc";
      };
    };
    "dateformat-1.0.2-1.2.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "1.0.2-1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz";
        sha1 = "b0220c02de98617433b72851cf47de3df2cdbee9";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "findup-sync-0.1.3" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.3.tgz";
        sha1 = "7f3e7a97b82392c653bf06589bd85190e93c3683";
      };
    };
    "glob-3.1.21" = {
      name = "glob";
      packageName = "glob";
      version = "3.1.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.1.21.tgz";
        sha1 = "d29e0a055dea5138f4d07ed40e8982e83c2066cd";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha1 = "b834f723cc4a242aa65963459df6d984c5d3d959";
      };
    };
    "iconv-lite-0.2.11" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz";
        sha1 = "1ce60a3a57864a292d1321ff4609ca4bb965adc8";
      };
    };
    "minimatch-0.2.14" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz";
        sha1 = "c74e780574f63c6f9a090e90efbe6ef53a6a756a";
      };
    };
    "nopt-1.0.10" = {
      name = "nopt";
      packageName = "nopt";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz";
        sha1 = "6ddd21bd2a31417b92727dd585f8a6f37608ebee";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "lodash-0.9.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-0.9.2.tgz";
        sha1 = "8f3499c5245d346d682e5b0d3b40767e09f1a92c";
      };
    };
    "underscore.string-2.2.1" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz";
        sha1 = "d7c0fa2af5d5a1a67f4253daee98132e733f0f19";
      };
    };
    "which-1.0.9" = {
      name = "which";
      packageName = "which";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.0.9.tgz";
        sha1 = "460c1da0f810103d0321a9b633af9e575e64486f";
      };
    };
    "js-yaml-2.0.5" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-2.0.5.tgz";
        sha1 = "a25ae6509999e97df278c6719da11bd0687743a8";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha1 = "0632638f8d877cc82107d30a0fff1a17cba1cd0c";
      };
    };
    "getobject-0.1.0" = {
      name = "getobject";
      packageName = "getobject";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-0.1.0.tgz";
        sha1 = "047a449789fa160d018f5486ed91320b6ec7885c";
      };
    };
    "grunt-legacy-util-0.2.0" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-0.2.0.tgz";
        sha1 = "93324884dbf7e37a9ff7c026dff451d94a9e554b";
      };
    };
    "grunt-legacy-log-0.1.3" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-0.1.3.tgz";
        sha1 = "ec29426e803021af59029f87d2f9cd7335a05531";
      };
    };
    "glob-3.2.11" = {
      name = "glob";
      packageName = "glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.2.11.tgz";
        sha1 = "4a973f635b9190f715d10987d5c00fd2815ebe3d";
      };
    };
    "lodash-2.4.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz";
        sha1 = "fadd834b9683073da179b3eae6d9c0d15053f73e";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-0.3.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz";
        sha1 = "275d8edaac4f1bb3326472089e7949c8394699dd";
      };
    };
    "lru-cache-2.7.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz";
        sha1 = "6d4524e8b955f95d4f5b58851ce21dd72fb4e952";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "graceful-fs-1.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz";
        sha1 = "15a4806a57547cb2d2dbf27f42e89a8c3451b364";
      };
    };
    "inherits-1.0.2" = {
      name = "inherits";
      packageName = "inherits";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-1.0.2.tgz";
        sha1 = "ca4309dadee6b54cc0b8d247e8d7c7a0975bdc9b";
      };
    };
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "38s4f3id97wsb0rg9nm9zvxyq0nvwrmrpa5dzvrkp36mf5ibs98b4z6lvsbrwzzs0sbcank6c7gpp06vcwp9acfhp41rzlhi3ybsxwy";
      };
    };
    "argparse-0.1.16" = {
      name = "argparse";
      packageName = "argparse";
      version = "0.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz";
        sha1 = "cfd01e0fbba3d6caed049fbd758d40f65196f57c";
      };
    };
    "esprima-1.0.4" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz";
        sha1 = "9f557e08fc3b4d26ece9dd34f8fbf476b62585ad";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "underscore.string-2.4.0" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.4.0.tgz";
        sha1 = "8cdd8fbac4e2d2ea1e7e2e8097c42f442280f85b";
      };
    };
    "grunt-legacy-log-utils-0.1.1" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-0.1.1.tgz";
        sha1 = "c0706b9dd9064e116f36f23fe4e6b048672c0f7e";
      };
    };
    "underscore.string-2.3.3" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz";
        sha1 = "71c08bf6b428b1133f37e78fa3a21c82f7329b0d";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "file-sync-cmp-0.1.1" = {
      name = "file-sync-cmp";
      packageName = "file-sync-cmp";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-sync-cmp/-/file-sync-cmp-0.1.1.tgz";
        sha1 = "a5e7a8ffbfa493b43b923bbd4ca89a53b63b612b";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "chalk-0.5.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-0.5.1.tgz";
        sha1 = "663b3a648b68b55d04690d49167aa837858f2174";
      };
    };
    "source-map-0.3.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.3.0.tgz";
        sha1 = "8586fb9a5a005e5b501e21cd18b6f21b457ad1f9";
      };
    };
    "ansi-styles-1.1.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-1.1.0.tgz";
        sha1 = "eaecbf66cd706882760b2f4691582b8f55d7a7de";
      };
    };
    "has-ansi-0.1.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-0.1.0.tgz";
        sha1 = "84f265aae8c0e6a88a12d7022894b7568894c62e";
      };
    };
    "strip-ansi-0.3.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-0.3.0.tgz";
        sha1 = "25f48ea22ca79187f3174a4db8759347bb126220";
      };
    };
    "supports-color-0.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-0.2.0.tgz";
        sha1 = "d92de2694eb3f67323973d7ae3d8b55b4c22190a";
      };
    };
    "ansi-regex-0.2.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-0.2.1.tgz";
        sha1 = "0d8e946967a3d8143f93e24e298525fc1b2235f9";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "async-2.5.0" = {
      name = "async";
      packageName = "async";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.5.0.tgz";
        sha512 = "1ijrwmifg76a8wwhhfqxg23kd0rsjhzklwvj2czvqxs2k25ii6p3y6s3vhbcc5hnr87b0gfc4nb54b8bph2hn9c6z1f6nldjw04ksbv";
      };
    };
    "less-2.7.3" = {
      name = "less";
      packageName = "less";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-2.7.3.tgz";
        sha512 = "04jbm6adzhknlcwjjdd94n8dhqwgsg0fyampis9854jf23z9g9lxs8593908ymwldl88bjipf9b9rw6xfibb29vv7s0c44wllj4ixr8";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "errno-0.1.4" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.4.tgz";
        sha1 = "b896e23a9e5e8ba33871fc996abd3635fc9a1c7d";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "image-size-0.5.5" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz";
        sha1 = "09dfd4ab9d20e29eb1c3e80b8990378df9e3cb9c";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "2sz22r1xrnyvq6jg0h6b6cab3s3xdsfqa0n6vl9xv9gq3ppcxrcpg2hqfc41xjwnfwfkr6240l5gys7nds61ch6xcb3gr3fwsl7x398";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "17cn4nns2nxh9r0pdiqsqx3fpvaa82c1mhcr8r84k2a9hkpb0mj4bxzfbg3l9iy74yn9hj6mh2gsddsi3v939a1zp7ycbzqkxfm12cy";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "request-2.81.0" = {
      name = "request";
      packageName = "request";
      version = "2.81.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.81.0.tgz";
        sha1 = "c6928946a0e06c5f8d6f8a9333469ffda46298a0";
      };
    };
    "prr-0.0.0" = {
      name = "prr";
      packageName = "prr";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-0.0.0.tgz";
        sha1 = "1a84b85908325501411853d0081ee3fa86e2926a";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "har-validator-4.2.1" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-4.2.1.tgz";
        sha1 = "33481d0f1bbff600dd203d75812a6a5fba002e2a";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "performance-now-0.2.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-0.2.0.tgz";
        sha1 = "33ef30c5c77d4ea21c5a53869d91b56d8f2555e5";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.3.tgz";
        sha1 = "0b618a5565b6dea90bf3425d04d55edc475a7561";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "uuid-3.1.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz";
        sha512 = "3x5mi85l1559nkb35pfksjjgiyfyqrcvmcf0nly1xjl1kb0d37jnxd6sk0b8d331waadnqbf60nfssb563x9pvnjcw87lrh976sv18c";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-4.11.8" = {
      name = "ajv";
      packageName = "ajv";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-4.11.8.tgz";
        sha1 = "82ffb02b29e662ae53bdc20af15947706739c536";
      };
    };
    "har-schema-1.0.5" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-1.0.5.tgz";
        sha1 = "d263135f43307c02c602afc8fe95970c0151369e";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "gaze-0.5.2" = {
      name = "gaze";
      packageName = "gaze";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaze/-/gaze-0.5.2.tgz";
        sha1 = "40b709537d24d1d45767db5a908689dfe69ac44f";
      };
    };
    "tiny-lr-fork-0.0.5" = {
      name = "tiny-lr-fork";
      packageName = "tiny-lr-fork";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-lr-fork/-/tiny-lr-fork-0.0.5.tgz";
        sha1 = "1e99e1e2a8469b736ab97d97eefa98c71f76ed0a";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "globule-0.1.0" = {
      name = "globule";
      packageName = "globule";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globule/-/globule-0.1.0.tgz";
        sha1 = "d9c8edde1da79d125a151b79533b978676346ae5";
      };
    };
    "lodash-1.0.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-1.0.2.tgz";
        sha1 = "8f57560c83b59fc270bd3d561b690043430e2551";
      };
    };
    "qs-0.5.6" = {
      name = "qs";
      packageName = "qs";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-0.5.6.tgz";
        sha1 = "31b1ad058567651c526921506b9a8793911a0384";
      };
    };
    "faye-websocket-0.4.4" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.4.4.tgz";
        sha1 = "c14c5b3bf14d7417ffbfd990c0a7495cd9f337bc";
      };
    };
    "noptify-0.0.3" = {
      name = "noptify";
      packageName = "noptify";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/noptify/-/noptify-0.0.3.tgz";
        sha1 = "58f654a73d9753df0c51d9686dc92104a67f4bbb";
      };
    };
    "debug-0.7.4" = {
      name = "debug";
      packageName = "debug";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-0.7.4.tgz";
        sha1 = "06e1ea8082c2cb14e39806e22e2f6f757f92af39";
      };
    };
    "nopt-2.0.0" = {
      name = "nopt";
      packageName = "nopt";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-2.0.0.tgz";
        sha1 = "ca7416f20a5e3f9c3b86180f96295fa3d0b52e0d";
      };
    };
    "command-line-args-3.0.5" = {
      name = "command-line-args";
      packageName = "command-line-args";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-args/-/command-line-args-3.0.5.tgz";
        sha1 = "5bd4ad45e7983e5c1344918e40280ee2693c5ac0";
      };
    };
    "command-line-usage-3.0.8" = {
      name = "command-line-usage";
      packageName = "command-line-usage";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-usage/-/command-line-usage-3.0.8.tgz";
        sha1 = "b6a20978c1b383477f5c11a529428b880bfe0f4d";
      };
    };
    "dom5-1.3.6" = {
      name = "dom5";
      packageName = "dom5";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom5/-/dom5-1.3.6.tgz";
        sha1 = "a7088a9fc5f3b08dc9f6eda4c7abaeb241945e0d";
      };
    };
    "array-back-1.0.4" = {
      name = "array-back";
      packageName = "array-back";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-1.0.4.tgz";
        sha1 = "644ba7f095f7ffcf7c43b5f0dc39d3c1f03c063b";
      };
    };
    "feature-detect-es6-1.3.1" = {
      name = "feature-detect-es6";
      packageName = "feature-detect-es6";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/feature-detect-es6/-/feature-detect-es6-1.3.1.tgz";
        sha1 = "f888736af9cb0c91f55663bfa4762eb96ee7047f";
      };
    };
    "find-replace-1.0.3" = {
      name = "find-replace";
      packageName = "find-replace";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-replace/-/find-replace-1.0.3.tgz";
        sha1 = "b88e7364d2d9c959559f388c66670d6130441fa0";
      };
    };
    "typical-2.6.1" = {
      name = "typical";
      packageName = "typical";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-2.6.1.tgz";
        sha1 = "5c080e5d661cbbe38259d2e70a3c7253e873881d";
      };
    };
    "test-value-2.1.0" = {
      name = "test-value";
      packageName = "test-value";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/test-value/-/test-value-2.1.0.tgz";
        sha1 = "11da6ff670f3471a73b625ca4f3fdcf7bb748291";
      };
    };
    "ansi-escape-sequences-3.0.0" = {
      name = "ansi-escape-sequences";
      packageName = "ansi-escape-sequences";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escape-sequences/-/ansi-escape-sequences-3.0.0.tgz";
        sha1 = "1c18394b6af9b76ff9a63509fa497669fd2ce53e";
      };
    };
    "table-layout-0.3.0" = {
      name = "table-layout";
      packageName = "table-layout";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/table-layout/-/table-layout-0.3.0.tgz";
        sha1 = "6ee20dc483db371b3e5c87f704ed2f7c799d2c9a";
      };
    };
    "core-js-2.5.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz";
        sha1 = "ae6874dc66937789b80754ff5428df66819ca50b";
      };
    };
    "deep-extend-0.4.2" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.2.tgz";
        sha1 = "48b699c27e334bf89f10892be432f6e4c7d34a7f";
      };
    };
    "wordwrapjs-2.0.0" = {
      name = "wordwrapjs";
      packageName = "wordwrapjs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-2.0.0.tgz";
        sha1 = "ab55f695e6118da93858fdd70c053d1c5e01ac20";
      };
    };
    "reduce-flatten-1.0.1" = {
      name = "reduce-flatten";
      packageName = "reduce-flatten";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-flatten/-/reduce-flatten-1.0.1.tgz";
        sha1 = "258c78efd153ddf93cb561237f61184f3696e327";
      };
    };
    "@types/clone-0.1.30" = {
      name = "@types/clone";
      packageName = "@types/clone";
      version = "0.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/clone/-/clone-0.1.30.tgz";
        sha1 = "e7365648c1b42136a59c7d5040637b3b5c83b614";
      };
    };
    "@types/node-4.2.21" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "4.2.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-4.2.21.tgz";
        sha512 = "1chfy6346myh3h9la423cpyymrvmm2qyk9wfaqafyzpj296b4j3g1xr9ca3is3hsqxkvph5dr1dkjj4r15il6ihr12gsvb4c16i6mwg";
      };
    };
    "@types/parse5-0.0.31" = {
      name = "@types/parse5";
      packageName = "@types/parse5";
      version = "0.0.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse5/-/parse5-0.0.31.tgz";
        sha1 = "e827a493a443b156e1b582a2e4c3bdc0040f2ee7";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "parse5-1.5.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-1.5.1.tgz";
        sha1 = "9b7f3b0de32be78dc2401b17573ccaf0f6f59d94";
      };
    };
    "@types/node-6.0.90" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "6.0.90";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-6.0.90.tgz";
        sha512 = "2q3rymdpikk7mc1rlmv8r1n0rlw856xmw64dx65mi90khgn1plppcsal3jvcbbhc527f06fh2wk9yargn2mlmgxxibhdvv2ax2hcymm";
      };
    };
    "es6-promise-2.3.0" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz";
        sha1 = "96edb9f2fdb01995822b263dd8aadab6748181bc";
      };
    };
    "hydrolysis-1.25.0" = {
      name = "hydrolysis";
      packageName = "hydrolysis";
      version = "1.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hydrolysis/-/hydrolysis-1.25.0.tgz";
        sha1 = "a4fb14a37a1e03b0db52d8aaa57c682272a14d84";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "path-posix-1.0.0" = {
      name = "path-posix";
      packageName = "path-posix";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-posix/-/path-posix-1.0.0.tgz";
        sha1 = "06b26113f56beab042545a23bfa88003ccac260f";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "babel-polyfill-6.26.0" = {
      name = "babel-polyfill";
      packageName = "babel-polyfill";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-polyfill/-/babel-polyfill-6.26.0.tgz";
        sha1 = "379937abc67d7895970adc621f284cd966cf2153";
      };
    };
    "doctrine-0.7.2" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-0.7.2.tgz";
        sha1 = "7cb860359ba3be90e040b26b729ce4bfa654c523";
      };
    };
    "dom5-1.1.0" = {
      name = "dom5";
      packageName = "dom5";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom5/-/dom5-1.1.0.tgz";
        sha1 = "3a0c7700c083ab4c4d26938a78b0f0c6dcc37794";
      };
    };
    "escodegen-1.9.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.9.0.tgz";
        sha512 = "0il8dp1bh3n1am3xx5pazmpjb5m8wzdn9xg1lgh4j8axvsy8v24i1171c04qafx0j4xsaq76j29ljq2srf4i3kdl3qbrn9psjy1hhxz";
      };
    };
    "espree-3.5.1" = {
      name = "espree";
      packageName = "espree";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-3.5.1.tgz";
        sha1 = "0c988b8ab46db53100a1954ae4ba995ddd27d87e";
      };
    };
    "estraverse-3.1.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-3.1.0.tgz";
        sha1 = "15e28a446b8b82bc700ccc8b96c78af4da0d6cba";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "regenerator-runtime-0.10.5" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.10.5.tgz";
        sha1 = "336c3efc1220adcedda2c9fab67b5a7955a33658";
      };
    };
    "regenerator-runtime-0.11.0" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.0.tgz";
        sha512 = "3a1pn2aankj443h5v8png8dbgrlyb7fcdn66vjglxwqvdpivpq959qsl2n44i6zwf1k5y6y23xwhim0x077yy275dyr6vwiny83987x";
      };
    };
    "esutils-1.1.6" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.1.6.tgz";
        sha1 = "c01ccaa9ae4b897c6d0c3e210ae52f3c7a844375";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "acorn-5.2.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.2.1.tgz";
        sha512 = "3ryzhy30vzfnn2a0crafh3qsrx145ali8i88q1bc0lzl1dz0ycmjmmwh2yn9xfjs3vmjxl7nphpwcs4imgz3da5jb8fvjqbrvnjwvcc";
      };
    };
    "acorn-jsx-3.0.1" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz";
        sha1 = "afdf9488fb1ecefc8348f6fb22f464e32a58b36b";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "crisper-1.2.0" = {
      name = "crisper";
      packageName = "crisper";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crisper/-/crisper-1.2.0.tgz";
        sha1 = "9a91f597d71f6110294e076ad44dbb3408568e46";
      };
    };
    "cli-1.0.1" = {
      name = "cli";
      packageName = "cli";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli/-/cli-1.0.1.tgz";
        sha1 = "22817534f24bfa4950c34d532d48ecbc621b8c14";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "htmlparser2-3.8.3" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz";
        sha1 = "996c28b191516a8be86501a7d79757e5c70c1068";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "shelljs-0.3.0" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz";
        sha1 = "3596e6307a781544f591f37da618360f31db57b1";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "lodash-3.7.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.7.0.tgz";
        sha1 = "3678bd8ab995057c07ade836ed2ef087da811d45";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "domhandler-2.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz";
        sha1 = "2de59a0822d5027fabff6f032c2b25a2a8abe738";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "entities-1.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.0.0.tgz";
        sha1 = "b2987aa3821347fcde642b24fdfc9e4fb712bf26";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
  };
  args = {
    name = "rhodecode-enterprise";
    packageName = "rhodecode-enterprise";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."grunt-0.4.5"
      sources."grunt-contrib-copy-1.0.0"
      (sources."grunt-contrib-concat-0.5.1" // {
        dependencies = [
          sources."chalk-0.5.1"
          sources."ansi-styles-1.1.0"
          sources."has-ansi-0.1.0"
          sources."strip-ansi-0.3.0"
          sources."supports-color-0.2.0"
          sources."ansi-regex-0.2.1"
        ];
      })
      sources."grunt-contrib-jshint-0.12.0"
      (sources."grunt-contrib-less-1.4.1" // {
        dependencies = [
          sources."async-2.5.0"
          sources."lodash-4.17.4"
        ];
      })
      (sources."grunt-contrib-watch-0.6.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."async-0.2.10"
        ];
      })
      sources."crisper-2.1.1"
      (sources."vulcanize-1.16.0" // {
        dependencies = [
          sources."nopt-3.0.6"
        ];
      })
      sources."grunt-crisper-1.0.1"
      (sources."grunt-vulcanize-1.0.0" // {
        dependencies = [
          sources."crisper-1.2.0"
          sources."nopt-3.0.6"
        ];
      })
      (sources."jshint-2.9.5" // {
        dependencies = [
          sources."minimatch-3.0.4"
          sources."lodash-3.7.0"
        ];
      })
      sources."bower-1.8.2"
      sources."favico.js-0.3.10"
      sources."appenlight-client-git+https://git@github.com/AppEnlight/appenlight-client-js.git#0.5.0"
      sources."async-0.1.22"
      sources."coffee-script-1.3.3"
      sources."colors-0.6.2"
      sources."dateformat-1.0.2-1.2.3"
      sources."eventemitter2-0.4.14"
      (sources."findup-sync-0.1.3" // {
        dependencies = [
          sources."glob-3.2.11"
          sources."lodash-2.4.2"
          sources."minimatch-0.3.0"
        ];
      })
      (sources."glob-3.1.21" // {
        dependencies = [
          sources."inherits-1.0.2"
        ];
      })
      sources."hooker-0.2.3"
      sources."iconv-lite-0.2.11"
      sources."minimatch-0.2.14"
      sources."nopt-1.0.10"
      sources."rimraf-2.2.8"
      sources."lodash-0.9.2"
      sources."underscore.string-2.2.1"
      sources."which-1.0.9"
      sources."js-yaml-2.0.5"
      sources."exit-0.1.2"
      sources."getobject-0.1.0"
      sources."grunt-legacy-util-0.2.0"
      (sources."grunt-legacy-log-0.1.3" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."inherits-2.0.3"
      sources."lru-cache-2.7.3"
      sources."sigmund-1.0.1"
      sources."graceful-fs-1.2.3"
      sources."abbrev-1.1.1"
      (sources."argparse-0.1.16" // {
        dependencies = [
          sources."underscore.string-2.4.0"
        ];
      })
      sources."esprima-1.0.4"
      sources."underscore-1.7.0"
      (sources."grunt-legacy-log-utils-0.1.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."chalk-1.1.3"
      sources."file-sync-cmp-0.1.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.1.1"
      sources."source-map-0.3.0"
      sources."amdefine-1.0.1"
      (sources."less-2.7.3" // {
        dependencies = [
          sources."graceful-fs-4.1.11"
          sources."source-map-0.5.7"
        ];
      })
      sources."errno-0.1.4"
      sources."image-size-0.5.5"
      sources."mime-1.4.1"
      sources."mkdirp-0.5.1"
      sources."promise-7.3.1"
      sources."request-2.81.0"
      sources."prr-0.0.0"
      sources."minimist-0.0.8"
      sources."asap-2.0.6"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."caseless-0.12.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.1"
      sources."forever-agent-0.6.1"
      sources."form-data-2.1.4"
      sources."har-validator-4.2.1"
      sources."hawk-3.1.3"
      sources."http-signature-1.1.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.17"
      sources."oauth-sign-0.8.2"
      sources."performance-now-0.2.0"
      sources."qs-6.4.0"
      sources."safe-buffer-5.1.1"
      sources."stringstream-0.0.5"
      sources."tough-cookie-2.3.3"
      sources."tunnel-agent-0.6.0"
      sources."uuid-3.1.0"
      sources."delayed-stream-1.0.0"
      sources."asynckit-0.4.0"
      sources."ajv-4.11.8"
      sources."har-schema-1.0.5"
      sources."co-4.6.0"
      sources."json-stable-stringify-1.0.1"
      sources."jsonify-0.0.0"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."assert-plus-0.2.0"
      (sources."jsprim-1.4.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."sshpk-1.13.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."extsprintf-1.3.0"
      sources."json-schema-0.2.3"
      (sources."verror-1.10.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."core-util-is-1.0.2"
      sources."asn1-0.2.3"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."getpass-0.1.7" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."mime-db-1.30.0"
      sources."punycode-1.4.1"
      sources."gaze-0.5.2"
      (sources."tiny-lr-fork-0.0.5" // {
        dependencies = [
          sources."qs-0.5.6"
        ];
      })
      (sources."globule-0.1.0" // {
        dependencies = [
          sources."lodash-1.0.2"
        ];
      })
      sources."faye-websocket-0.4.4"
      (sources."noptify-0.0.3" // {
        dependencies = [
          sources."nopt-2.0.0"
        ];
      })
      sources."debug-0.7.4"
      sources."command-line-args-3.0.5"
      sources."command-line-usage-3.0.8"
      sources."dom5-1.3.6"
      sources."array-back-1.0.4"
      sources."feature-detect-es6-1.3.1"
      sources."find-replace-1.0.3"
      sources."typical-2.6.1"
      sources."test-value-2.1.0"
      sources."ansi-escape-sequences-3.0.0"
      sources."table-layout-0.3.0"
      sources."core-js-2.5.1"
      sources."deep-extend-0.4.2"
      sources."wordwrapjs-2.0.0"
      sources."reduce-flatten-1.0.1"
      sources."@types/clone-0.1.30"
      sources."@types/node-4.2.21"
      (sources."@types/parse5-0.0.31" // {
        dependencies = [
          sources."@types/node-6.0.90"
        ];
      })
      sources."clone-1.0.2"
      sources."parse5-1.5.1"
      sources."es6-promise-2.3.0"
      (sources."hydrolysis-1.25.0" // {
        dependencies = [
          sources."dom5-1.1.0"
        ];
      })
      sources."path-posix-1.0.0"
      sources."acorn-3.3.0"
      sources."babel-polyfill-6.26.0"
      sources."doctrine-0.7.2"
      (sources."escodegen-1.9.0" // {
        dependencies = [
          sources."estraverse-4.2.0"
          sources."esutils-2.0.2"
          sources."esprima-3.1.3"
          sources."source-map-0.5.7"
        ];
      })
      (sources."espree-3.5.1" // {
        dependencies = [
          sources."acorn-5.2.1"
        ];
      })
      sources."estraverse-3.1.0"
      sources."path-is-absolute-1.0.1"
      (sources."babel-runtime-6.26.0" // {
        dependencies = [
          sources."regenerator-runtime-0.11.0"
        ];
      })
      sources."regenerator-runtime-0.10.5"
      sources."esutils-1.1.6"
      sources."isarray-0.0.1"
      sources."optionator-0.8.2"
      sources."prelude-ls-1.1.2"
      sources."deep-is-0.1.3"
      sources."wordwrap-1.0.0"
      sources."type-check-0.3.2"
      sources."levn-0.3.0"
      sources."fast-levenshtein-2.0.6"
      sources."acorn-jsx-3.0.1"
      sources."object-assign-4.1.1"
      (sources."cli-1.0.1" // {
        dependencies = [
          sources."glob-7.1.2"
          sources."minimatch-3.0.4"
        ];
      })
      sources."console-browserify-1.1.0"
      sources."htmlparser2-3.8.3"
      sources."shelljs-0.3.0"
      sources."strip-json-comments-1.0.4"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.6"
      sources."once-1.4.0"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.8"
      sources."balanced-match-1.0.0"
      sources."concat-map-0.0.1"
      sources."date-now-0.1.4"
      sources."domhandler-2.3.0"
      sources."domutils-1.5.1"
      sources."domelementtype-1.3.0"
      sources."readable-stream-1.1.14"
      sources."entities-1.0.0"
      (sources."dom-serializer-0.1.0" // {
        dependencies = [
          sources."domelementtype-1.1.3"
          sources."entities-1.1.1"
        ];
      })
      sources."string_decoder-0.10.31"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}